### ISSUE TITLE
Setting up HDD as a kick drum

### ISSUE THREAD

**Issue by GenericPNP** [SammyIAm/Moppy2#46] opened 2019-02-06 22:58 UTC
Would I need to alter the code and how would I wire it to the HDD from the Arduino? Do I wire straight to the hard drive motor?

**Comment by SammyIAm** [comment] 2019-02-21 20:49
Closing as duplicate of issue #44 .  There's some info there that might be helpful, though you may need to reask your question there if it's not sufficiently answered (I don't actually have any experience so I don't know if you can direct-wire the HDD arm, or if you you need a transistor go-between)

**Closed by SammyIAm** 2019-02-21 20:49 UTC
